# This is a basic workflow to build a Flatpak using GitHub Actions

name: Build Flatpak

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows manual trigger from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install Flatpak tools
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder desktop-file-utils wget jq

      # Add Flathub and install Flatpak runtimes
      - name: Set up Flatpak environment
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user --noninteractive flathub \
            org.freedesktop.Platform//23.08 \
            org.freedesktop.Sdk//23.08 \
            org.electronjs.Electron2.BaseApp//23.08

      # Fix expected Flatpak directories
      - name: Ensure Flatpak sandbox paths exist
        run: |
          mkdir -p ~/.local/share/flatpak/exports/share
          mkdir -p ~/.var/app

      # Build the Flatpak
      - name: Build Popcorn Time Flatpak
        run: |
          flatpak-builder --force-clean --user \
            --install \
            --repo=repo \
            build-dir \
            org.popcorntime.PopcornTime.json

      # Bundle it into a .flatpak file
      - name: Create Flatpak bundle
        run: |
          flatpak build-bundle repo PopcornTime.flatpak org.popcorntime.PopcornTime

      # Upload the bundle as an artifact
      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: PopcornTime.flatpak
          path: PopcornTime.flatpak
