name: Build Flatpak

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flatpak
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder wget gnome-desktop-testing

          # Add Flathub
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

          # Install runtimes (adjust if needed)
          flatpak install -y --noninteractive flathub \
            org.freedesktop.Platform//23.08 \
            org.freedesktop.Sdk//23.08 \
            org.electronjs.Electron2.BaseApp//23.08

      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean --user build-dir org.popcorntime.PopcornTime.json

      - name: Bundle Flatpak
        run: |
          flatpak build-bundle build-dir PopcornTime.flatpak org.popcorntime.PopcornTime

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v3
        with:
          name: PopcornTime.flatpak
          path: PopcornTime.flatpak
